### ISSUE TITLE
When selecting and moving unselected object in front of selected object, it jumps

### ISSUE THREAD

**Issue by eyal0** [eyal0/OctoPrint-Slicer#5]
To reproduce:

1. Put two objects on platform and adjust view so that one partially obscures the other.
2. Select the object that is partially obscured.
3. Now drag to move the object that obscures.  It will jump and then drag normally.

Like this:

![jumping_stl](https://cloud.githubusercontent.com/assets/109809/25122625/434f5064-242e-11e7-9737-2008b4532cb8.gif)

**Comment by kennethjiang** [comment]
It is a very good catch!

It looks like a tricky bug that needs some digging. I'm going on vacation for a few days. Will take a stab at it when I'm back.

**Comment by eyal0** [comment]
@kennethjiang Figured it out.  The order of `addEventListeners` needed adjusting.  The patch is ready for you.  It was tricky.  I put some breakpoints and got lucky.
